### ISSUE TITLE
The discovery Service must get the redis configurations from the MinosConfig file

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/discovery#2]
```yaml
discovery:
    ....
    db:
        host: localhost
        port: 6379
        password:

```
